/// <reference types="node" />
export * from './errors';
import { Config } from './config';
import { Server } from './server';
import { FederationServer } from './federation_server';
import { StellarTomlResolver } from './stellar_toml_resolver';
export { default as HorizonAxiosClient } from './horizon_axios_client';
import * as stellarBase from 'stellar-base';
declare const _default: {
    hash(data: Buffer): Buffer;
    sign(data: Buffer, rawSecret: Buffer): Buffer;
    verify(data: Buffer, signature: Buffer, rawPublicKey: Buffer): boolean;
    Account: typeof stellarBase.Account;
    Asset: typeof stellarBase.Asset;
    FastSigning: boolean;
    Keypair: typeof stellarBase.Keypair;
    MemoNone: "none";
    MemoID: "id";
    MemoText: "text";
    MemoHash: "hash";
    MemoReturn: "return";
    Memo: typeof stellarBase.Memo;
    Networks: typeof stellarBase.Networks;
    Network: typeof stellarBase.Network;
    AuthRequiredFlag: 1;
    AuthRevocableFlag: 2;
    AuthImmutableFlag: 4;
    Operation: typeof stellarBase.Operation;
    StrKey: typeof stellarBase.StrKey;
    Transaction: typeof stellarBase.Transaction;
    TimeoutInfinite: 0;
    TransactionBuilder: typeof stellarBase.TransactionBuilder;
    xdr: typeof stellarBase.xdr;
    Config: typeof Config;
    Server: typeof Server;
    FederationServer: typeof FederationServer;
    FEDERATION_RESPONSE_MAX_SIZE: number;
    StellarTomlResolver: typeof StellarTomlResolver;
    STELLAR_TOML_MAX_SIZE: number;
};
export default _default;
